version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xmx1g -Xms1g
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 2g
          cpus: "1.0"
        reservations:
          memory: 1g
          cpus: "0.5"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:8.9.2
    ports:
      - "5044:5044"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
        reservations:
          memory: 512m
          cpus: "0.25"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:8.9.2
    ports:
      - "5601:5601"
    deploy:
      resources:
        limits:
          memory: 1g
          cpus: "0.5"
        reservations:
          memory: 512m
          cpus: "0.25"
    networks:
      - elk

networks:
  elk:
    driver: bridge
